# STEP 1 : GO ANNOTATIONS EXTRACTION FROM AGR

In [ ]:
import pandas as pd
import obonet
gaf_path = r"downloaded_data_ontology_related\wb.gaf"  # WormBase database of biology (wb), https://current.geneontology.org/products/pages/downloads.html

gaf_cols = [
    "DB",
    "DB_Object_ID",
    "DB_Object_Symbol",
    "Qualifier",
    "GO_ID",
    "DB_Reference",
    "Evidence_Code",
    "With_or_From",
    "Aspect",
    "DB_Object_Name",
    "DB_Object_Synonym",
    "DB_Object_Type",
    "Taxon",
    "Date",
    "Assigned_By",
    "Annotation_Extension",
    "Gene_Product_Form_ID",
]

AGR_GO_ANNOTATION_df = pd.read_csv(
    gaf_path,
    sep="\t",
    comment="!",
    header=None,
    names=gaf_cols,
)

AGR_GO_ANNOTATION_df= AGR_GO_ANNOTATION_df.rename(columns={"DB_Object_Symbol":"Gene Symbol"})

AGR_GO_ANNOTATION_df

C:\Users\mikke\AppData\Local\Temp\ipykernel_9652\2427759559.py:25: DtypeWarning: Columns (0: Annotation_Extension, 1: Gene_Product_Form_ID) have mixed types. Specify dtype option on import or set low_memory=False.
  AGR_GO_ANNOTATION_df = pd.read_csv(

,DB,DB_Object_ID,Gene Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_or_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_By,Annotation_Extension,Gene_Product_Form_ID
0,WB,WBGene00000001,aap-1,enables,GO:0019901,PMID:12393910,IPI,UniProtKB:Q94125,F,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20151214,WB,NaN,WB:WBGene00000001
1,WB,WBGene00000001,aap-1,involved_in,GO:0008286,PMID:12393910,IGI,WB:WBGene00000090,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20151214,WB,NaN,WB:WBGene00000001
2,WB,WBGene00000001,aap-1,involved_in,GO:0008286,PMID:12393910,IGI,WB:WBGene00000898,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20151214,WB,NaN,WB:WBGene00000001
3,WB,WBGene00000001,aap-1,involved_in,GO:0008286,PMID:12393910,IMP,NaN,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20060302,WB,NaN,WB:WBGene00000001
4,WB,WBGene00000001,aap-1,involved_in,GO:0008340,PMID:12393910,IMP,NaN,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20060302,WB,NaN,WB:WBGene00000001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104765,WB,WBGene00003593,nfm-1,involved_in,GO:1902115,GO_REF:0000033,IBA,PANTHER:PTN001150648|ZFIN:ZDB-GENE-050803-1|Un...,P,FERM domain-containing protein,CELE_F42A10.2|F42A10.2|nfm-1,protein,taxon:6239,20210810,GO_Central,NaN,NaN
104766,WB,WBGene00011017,CELE_R04F11.5,involved_in,GO:0045039,GO_REF:0000033,IBA,PANTHER:PTN001086739|UniProtKB:Q9BSF4,P,Mitochondrial import inner membrane translocas...,CELE_R04F11.5|R04F11.5,protein,taxon:6239,20171130,GO_Central,NaN,NaN
104767,WB,WBGene00016120,vps-13d,involved_in,GO:0016236,GO_REF:0000033,IBA,PANTHER:PTN000414879|FB:FBgn0052113|dictyBase:...,P,Ricin B-type lectin domain-containing protein,C25H3.11|CELE_C25H3.11|vps-13D|vps-13d,protein,taxon:6239,20251104,GO_Central,NaN,NaN
104768,WB,WBGene00015397,nhr-149,involved_in,GO:0006357,GO_REF:0000033,IBA,PANTHER:PTN000638895|UniProtKB:P24468|UniProtK...,P,Nuclear Hormone Receptor family,C03G6.12|CELE_C03G6.12|nhr-149,protein,taxon:6239,20250903,GO_Central,NaN,NaN
104769,WB,WBGene00021934,cct-8,involved_in,GO:0006457,GO_REF:0000033,IBA,PANTHER:PTN004253040|UniProtKB:P17987|UniProtK...,P,T-complex protein 1 subunit theta,Y55F3AR.3|cct-8,protein,taxon:6239,20250902,GO_Central,NaN,NaN

# STEP 2: Full Gene ontology

In [6]:
full_ontology_schema_path = r"downloaded_data_ontology_related\gene_ontology_schema.obo" # https://obofoundry.org/ontology/go.html
 # https://obofoundry.org/ontology/go.html

graph = obonet.read_obo(full_ontology_schema_path)


#   Example data
#  {'GO:0000001': 'mitochondrion inheritance',
#  'GO:0000006': 'high-affinity zinc transmembrane transporter activity',
#  'GO:0000007': 'low-affinity zinc ion transmembrane transporter activity',
#  'GO:0000009': 'alpha-1,6-mannosyltransferase activity',
go_name_map = {
    go_id: data.get("name")
    for go_id, data in graph.nodes(data=True)
}
go_namespace_map = { #name space is 3 types: Root terms for the wb data: either molecular_function, biological_process or cellular_component
    go_id: data.get("namespace")
    for go_id, data in graph.nodes(data=True)
}

# MAP to existing GO_ID in the populated AGR data.
AGR_GO_ANNOTATION_df["GO_DESCRIPTION"] = AGR_GO_ANNOTATION_df["GO_ID"].map(go_name_map)
AGR_GO_ANNOTATION_df["GO_NAMESPACE"] = AGR_GO_ANNOTATION_df["GO_ID"].map(go_namespace_map)
AGR_GO_ANNOTATION_df

,DB,DB_Object_ID,Gene Symbol,Qualifier,GO_ID,DB_Reference,Evidence_Code,With_or_From,Aspect,DB_Object_Name,DB_Object_Synonym,DB_Object_Type,Taxon,Date,Assigned_By,Annotation_Extension,Gene_Product_Form_ID,GO_DESCRIPTION,GO_NAMESPACE
0,WB,WBGene00000001,aap-1,enables,GO:0019901,PMID:12393910,IPI,UniProtKB:Q94125,F,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20151214,WB,NaN,WB:WBGene00000001,protein kinase binding,molecular_function
1,WB,WBGene00000001,aap-1,involved_in,GO:0008286,PMID:12393910,IGI,WB:WBGene00000090,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20151214,WB,NaN,WB:WBGene00000001,insulin receptor signaling pathway,biological_process
2,WB,WBGene00000001,aap-1,involved_in,GO:0008286,PMID:12393910,IGI,WB:WBGene00000898,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20151214,WB,NaN,WB:WBGene00000001,insulin receptor signaling pathway,biological_process
3,WB,WBGene00000001,aap-1,involved_in,GO:0008286,PMID:12393910,IMP,NaN,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20060302,WB,NaN,WB:WBGene00000001,insulin receptor signaling pathway,biological_process
4,WB,WBGene00000001,aap-1,involved_in,GO:0008340,PMID:12393910,IMP,NaN,P,SH2 domain-containing protein,CELE_Y110A7A.10|Y110A7A.10|aap-1,protein,taxon:6239,20060302,WB,NaN,WB:WBGene00000001,determination of adult lifespan,biological_process
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104765,WB,WBGene00003593,nfm-1,involved_in,GO:1902115,GO_REF:0000033,IBA,PANTHER:PTN001150648|ZFIN:ZDB-GENE-050803-1|Un...,P,FERM domain-containing protein,CELE_F42A10.2|F42A10.2|nfm-1,protein,taxon:6239,20210810,GO_Central,NaN,NaN,regulation of organelle assembly,biological_process
104766,WB,WBGene00011017,CELE_R04F11.5,involved_in,GO:0045039,GO_REF:0000033,IBA,PANTHER:PTN001086739|UniProtKB:Q9BSF4,P,Mitochondrial import inner membrane translocas...,CELE_R04F11.5|R04F11.5,protein,taxon:6239,20171130,GO_Central,NaN,NaN,protein insertion into mitochondrial inner mem...,biological_process
104767,WB,WBGene00016120,vps-13d,involved_in,GO:0016236,GO_REF:0000033,IBA,PANTHER:PTN000414879|FB:FBgn0052113|dictyBase:...,P,Ricin B-type lectin domain-containing protein,C25H3.11|CELE_C25H3.11|vps-13D|vps-13d,protein,taxon:6239,20251104,GO_Central,NaN,NaN,macroautophagy,biological_process
104768,WB,WBGene00015397,nhr-149,involved_in,GO:0006357,GO_REF:0000033,IBA,PANTHER:PTN000638895|UniProtKB:P24468|UniProtK...,P,Nuclear Hormone Receptor family,C03G6.12|CELE_C03G6.12|nhr-149,protein,taxon:6239,20250903,GO_Central,NaN,NaN,regulation of transcription by RNA polymerase II,biological_process
104769,WB,WBGene00021934,cct-8,involved_in,GO:0006457,GO_REF:0000033,IBA,PANTHER:PTN004253040|UniProtKB:P17987|UniProtK...,P,T-complex protein 1 subunit theta,Y55F3AR.3|cct-8,protein,taxon:6239,20250902,GO_Central,NaN,NaN,protein folding,biological_process

# STEP 3: Simplicfication list based on ocurrence

In [ ]:
import pandas as pd


def send_upstream(go_id, graph, amount=1.0):

    upstream_bucket = {}

    def visit(term_id, weight):
        upstream_bucket[term_id] = upstream_bucket.get(term_id, 0.0) + weight

        parents = list(graph.successors(term_id))  # obonet: child -> parent

        if not parents:
            return

        split_weight = weight / len(parents)

        for parent_id in parents:
            visit(parent_id, split_weight)

    if pd.notna(go_id) and str(go_id) in graph:
        visit(str(go_id), amount)

    return upstream_bucket


def build_upstream_support(df, graph, go_id_col="GO_ID"):

    accumulation_bucket = {}

    go_counts = (
        df[go_id_col]
        .dropna()
        .astype(str)
        .value_counts()
        .to_dict()
    )

    for go_id, count in go_counts.items():
        upstream_bucket = send_upstream(
            go_id=go_id,
            graph=graph,
            amount=count,
        )

        for upstream_id, support in upstream_bucket.items():
            accumulation_bucket[upstream_id] = (
                accumulation_bucket.get(upstream_id, 0.0) + support
            )

    return accumulation_bucket


def upstream_support_to_df(upstream_support, graph):
    """
    Convert upstream support bucket into a readable dataframe.
    """
    rows = []

    for go_id, support in upstream_support.items():
        rows.append({
            "GO_ID": go_id,
            "GO_DESCRIPTION": graph.nodes[go_id].get("name", go_id)
            if go_id in graph else go_id,
            "GO_namespace": graph.nodes[go_id].get("namespace", pd.NA)
            if go_id in graph else pd.NA,
            "support_weight": support,
        })

    return (
        pd.DataFrame(rows)
        .sort_values("support_weight", ascending=False)
        .reset_index(drop=True)
    )

upstream_support = build_upstream_support(
    AGR_GO_ANNOTATION_df,
    graph=graph,
    go_id_col="GO_ID",
)

upstream_support_df = upstream_support_to_df(
    upstream_support,
    graph=graph,
)


upstream_support_df = upstream_support_df[3:59].sort_values(
    ["support_weight"], ascending=[False]) # same as AGR sizewise #removes the 3 roots

upstream_support_df = upstream_support_df.sort_values(
    ["GO_namespace", "support_weight"],
    ascending=[True, False],
).reset_index(drop=True)

upstream_support_df

,GO_ID,GO_DESCRIPTION,GO_namespace,support_weight
0,GO:0009987,cellular process,biological_process,20819.245807
1,GO:0008152,metabolic process,biological_process,11129.033442
2,GO:0051179,localization,biological_process,4055.091215
3,GO:0043170,macromolecule metabolic process,biological_process,3543.462105
4,GO:0032501,multicellular organismal process,biological_process,3326.979426
5,GO:0050896,response to stimulus,biological_process,3177.399232
6,GO:0051234,establishment of localization,biological_process,3106.823590
7,GO:0044238,primary metabolic process,biological_process,3097.837740
8,GO:0071840,cellular component organization or biogenesis,biological_process,3045.267178
9,GO:0032502,developmental process,biological_process,3021.752229
10,GO:0006810,transport,biological_process,2842.832364
11,GO:0007165,signal transduction,biological_process,2742.465837
12,GO:0016043,cellular component organization,biological_process,2666.897502
13,GO:0009059,macromolecule biosynthetic process,biological_process,2469.753734
14,GO:0090304,nucleic acid metabolic process,biological_process,1865.683444
15,GO:0050789,regulation of biological process,biological_process,1852.932495
16,GO:0048856,anatomical structure development,biological_process,1792.631063
17,GO:0009058,biosynthetic process,biological_process,1735.936106
18,GO:0010467,gene expression,biological_process,1709.982530
19,GO:0007275,multicellular organism development,biological_process,1460.382680
20,GO:0006351,DNA-templated transcription,biological_process,1394.467593
21,GO:0065007,biological regulation,biological_process,1357.283361
22,GO:0019538,protein metabolic process,biological_process,1320.178300
23,GO:0110165,cellular anatomical structure,cellular_component,29808.454861
24,GO:0043226,organelle,cellular_component,7647.385007
25,GO:0016020,membrane,cellular_component,6509.191165
26,GO:0043231,intracellular membrane-bounded organelle,cellular_component,6483.123296
27,GO:0005737,cytoplasm,cellular_component,5653.804720
28,GO:0005634,nucleus,cellular_component,5178.288194
29,GO:0005622,intracellular anatomical structure,cellular_component,5176.183248
30,GO:0043229,intracellular organelle,cellular_component,4609.728443
31,GO:0043227,membrane-bounded organelle,cellular_component,4128.347174
32,GO:0005886,plasma membrane,cellular_component,2651.638889
33,GO:0032991,protein-containing complex,cellular_component,2598.545139
34,GO:0043232,intracellular membraneless organelle,cellular_component,2211.006944
35,GO:0071944,cell periphery,cellular_component,1448.340278
36,GO:0005488,binding,molecular_function,13365.666667
37,GO:0003824,catalytic activity,molecular_function,12611.930556
38,GO:0005515,protein binding,molecular_function,5394.666667
39,GO:0016740,transferase activity,molecular_function,4331.229167
40,GO:0003676,nucleic acid binding,molecular_function,3402.666667
41,GO:0016787,hydrolase activity,molecular_function,2763.833333
42,GO:0036094,small molecule binding,molecular_function,2639.539583
43,GO:0005215,transporter activity,molecular_function,2276.329861
44,GO:0022857,transmembrane transporter activity,molecular_function,2239.079861
45,GO:0140096,"catalytic activity, acting on a protein",molecular_function,1920.791667
46,GO:0016772,"transferase activity, transferring phosphorus-...",molecular_function,1870.250000
47,GO:0043167,ion binding,molecular_function,1711.575000
48,GO:0004672,protein kinase activity,molecular_function,1684.125000
49,GO:0016491,oxidoreductase activity,molecular_function,1550.833333
50,GO:0003677,DNA binding,molecular_function,1466.666667
51,GO:0060089,molecular transducer activity,molecular_function,1347.906250
52,GO:0038023,signaling receptor activity,molecular_function,1347.906250
53,GO:0043169,cation binding,molecular_function,1278.200000
54,GO:0046872,metal ion binding,molecular_function,1258.000000
55,GO:0003723,RNA binding,molecular_function,1208.333333